---

version: 2

updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: friday
    assignees:
      - btkostner
    labels:
      - dependency

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
