app = "cockroach"

kill_signal = "SIGTERM"
kill_timeout = 90
services = []

[build]
  image = "ghcr.io/scrooge-life/cockroach:latest"

[checks]
  [checks.crdb]
    grace_period = "60s"
    interval = "15s"
    method = "get"
    path = "/health?ready=1"
    port = 8080
    protocol = "http"
    timeout = "10s"
    type = "http"

[deploy]
  strategy = "rolling"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[metrics]
  path = "/_status/vars"
  port = 8080

[[mounts]]
  destination = "/cockroach/cockroach-data"
  source = "crdb_data"
